export const mockMovies = [
  {
    imdbID: "tt0068646",
    Title: "El Padrino",
    Year: "1972",
    Rated: "R",
    Released: "24 Mar 1972",
    Runtime: "175 min",
    Genre: "Drama/Crimen",
    Director: "Francis Ford Coppola",
    Writer: "Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by)",
    Actors: "Marlon Brando, Al Pacino, James Caan",
    Plot: "El patriarca de una dinastía del crimen organizado transfiere el control de su imperio clandestino a su reacio hijo.",
    Language: "English, Italian, Latin",
    Country: "USA",
    Awards: "Won 3 Oscars. Another 29 wins & 30 nominations.",
    Poster: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    imdbRating: "9.2",
    imdbVotes: "1,620,367",
    Rating: 4.8
  },
  // Other movies will have placeholder data
  {
    imdbID: "tt0111161",
    Title: "Sueños de Fuga",
    Year: "1994",
    Rated: "R",
    Released: "14 Oct 1994",
    Runtime: "142 min",
    Genre: "Drama",
    Director: "Frank Darabont",
    Writer: "Stephen King (short story \"Rita Hayworth and Shawshank Redemption\"), Frank Darabont (screenplay)",
    Actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    Plot: "Dos hombres encarcelados se unen durante varios años, encontrando consuelo y una eventual redención a través de actos de decencia común.",
    Language: "English",
    Country: "USA",
    Awards: "Nominated for 7 Oscars. Another 21 wins & 36 nominations.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
    imdbRating: "9.3",
    imdbVotes: "2,343,113",
    Rating: 4.9
  },
];
